name: Build OCI Images

on:
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ci_type: pulp_ci_centos
            test_type: pulp_galaxy_ng
            test_image: pulp-galaxy-ng
          - ci_type: pulp_ci_centos
            test_type: pulp
            test_image: pulp
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: |
          wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
          # Apparently podman is slower to build the images
          sed -i "s/podman/docker/g" .ci/assets/ansible/build_container.yaml
          make build IMAGE=${{ matrix.ci_type }} TAG=latest
          make build IMAGE=${{ matrix.test_type }} TAG=latest
          docker images
      - name: Test the images
        run: assets/test.sh "pulp/${{ matrix.test_image }}:latest"
      - name: Display log on error
        if: failure()
        run: docker logs pulp

  sslbuild:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        include:
          - ci_type: pulp_ci_centos
            test_type: pulp_galaxy_ng
            test_image: pulp-galaxy-ng
          - ci_type: pulp_ci_centos
            test_type: pulp
            test_image: pulp
    steps:
      - uses: actions/checkout@v2
      - name: Build the images
        run: |
          wget https://github.com/just-containers/s6-overlay/releases/download/v1.22.1.0/s6-overlay-amd64.tar.gz
          # Apparently podman is slower to build the images
          sed -i "s/podman/docker/g" .ci/assets/ansible/build_container.yaml
          make build IMAGE=${{ matrix.ci_type }} TAG=https
          make build IMAGE=${{ matrix.test_type }} TAG=https
          docker images
        env:
          PY_COLORS: '1'
          ANSIBLE_FORCE_COLOR: '1'
        shell: bash
      - name: Test the images
        run: assets/test.sh "pulp/${{ matrix.test_image }}:https" https
      - name: Display log on error
        if: failure()
        run: docker logs pulp
